### ISSUE TITLE
Advice and questions

### ISSUE THREAD

**Issue by jkbbwr** [sustrik/libdill#124]
Why can't channels go between threads and why can't coroutines be migrated between threads?

**Comment by sustrik** [comment]
In libdill, the concurrency is supposed to be implemented using coroutines.

That works fine, but leaves you with the problem of how to utilize more than 1 core on a machine.

The idea is to launch as many processes as there are cores on the machine. Each process will consume 1 core leading to full utilization of the machine. If needed, communication between processes can be done using IPC.

That being said, some people have objections to the one-process-per-core model (e.g. IPC is slow, starting a process is slow etc.) In those cases you can start a new thread per core rather than new process. Still, there's a strict separation between the thread, similar to one you would have with proceses: no coroutine migration, no channels etc.

An additional point: If coroutines and channels worked in multi-threaded setting, they would have to be thread-safe and thus much slower.

**Comment by jkbbwr** [comment]
Okay so this is fine because I can just track what threads a coroutine lives in, my problem now is say a user spawns another coroutine at a later date that interacts with that first one, I could see they want to interact with a coroutine that is running on one thread and I could either schedule this coroutine on the same thread or if the thread is quite noisy migrate the existing coroutine. 

How could one migrate a coroutine inside one thread?

**Comment by sustrik** [comment]
Sorry, I don't follow. Migrate it where? To a different CPU core? If so, OS typically takes care of that. If your thread needs a lot of CPU it will eventually end up scheduled on a dedicated core. If your thread, OTOH, needs more processing power than one core, then that's not technically feasible. The best you can do is to add some kind of load balancer so that you won't end up in that situation in the first place.

**Comment by jkbbwr** [comment]
So I can spawn coroutines inside threads, but for channels to be usable both coroutines must be in the same thread. If I have spawned a coroutine inside a thread and need to talk to it from another how can I pause that coroutine and migrate it to a different thread

**Comment by sustrik** [comment]
So, AFAIU, you don't want migration, just communication between threads. Just use IPC for that. The added benefit is that if you at some later time decide to move the coroutine to a different process or machine, you can keep the code mostly unchanged.

**Comment by jkbbwr** [comment]
Like you said yourself though it bloats out the cost of using a "channel" plus I am limited by file descriptors. I tried building an mqueue system and it would crash at only a few hundred fds

**Comment by sustrik** [comment]
You are on OSX, right? They have artifically low maxfd limit. You can increase it manually.

**Comment by jkbbwr** [comment]
`Linux devbox2 4.10.13-1-ARCH #1 SMP PREEMPT Thu Apr 27 12:15:09 CEST 2017 x86_64 GNU/Linux`

I have tried increasing it, its not practical

**Comment by jkbbwr** [comment]
Shouldn't it be kinda trivial to implement work-stealing if coroutines were migratable.

I don't know C well enough reading the source to see why they are bound to the thread that created them.

**Comment by sustrik** [comment]
Having strongly separated threads/processes is the core design decision in this library. If IPC is not working for you there not much I can do.
