### ISSUE TITLE
Wrapping OS file descriptors

### ISSUE THREAD

**Issue by handicraftsman** [sustrik/libdill#152]
A "simple" case to demonstrate the problem: an N:M HTTP server. You cannot transfer ANY handles over threads. But you can transfer native file descriptors to worker threads using external queues to wrap them. The only problem is that you CANNOT wrap them in libdill handles. Maybe there should be a public interface for wrapping file descriptors into TCP/UDP handles? Or there's a better way to do that?

Note: this issue is almost a duplicate of [this one](https://github.com/sustrik/libdill/issues/117), but you closed it because issue creator was probably going to use that feature to wrap stdin/stdout.

**Comment by handicraftsman** [comment]
@sustrik

**Comment by sustrik** [comment]
The problem here is that libdill's TCP handle is statefull. It has a rx buffer. If you just detached the OS fd from the handle you'd be risking losing the data in the rx buffer.

One solution would be not to cache data in the handle, but then we would need to do (in the worst case e.g. for line based protocols such as SMTP) one system call per byte received. That's not really acceptable.

Another option would be to provide a mechanism for serialization of the entire handle. The serialized data could then be passed to another thread or even process (using SCM_RIGHTS to transfer the fd). However, this is rather complex problem and I don't have time to tackle it now.

Finally, you don't have to use libdill-provided TCP handles. libdill is perfectly OK working with native file descriptors (see fdin/fdout). You just have to make sure that the fd is in non-blocking mode so that you don't accidentally block the entire thread.

**Comment by handicraftsman** [comment]
What if i get these file descriptors using native API? Without detaching handles? Anyways, i want to use libdill's API because i'm actually trying to write an HTTP server and there's already an HTTP parsing/generating set of functions in libdill.

**Comment by sustrik** [comment]
The problem with that is that both you and libdill would then have access to the file descriptor. If you started  using it while it's wrapped in a libdill handle, it would result in undefined behavior.

This could be mitigated by the attach function making a dup of the file descriptor, then closing the original fd. But still, user can dup the fd before passing it to the attach function etc.

All that being said, I am OK with adding those functions but adding a big CAVEAT to the documentation.

**Comment by handicraftsman** [comment]
Yeah, thanks. That could be very useful if used properly.

**Comment by handicraftsman** [comment]
Can you please tell me how to edit your website docs? I'm not sure if i can just edit the HTML files in `website/` directory. (I'm trying to implement these functions by myself)

**Comment by sustrik** [comment]
From FAQ:

The source for the website is in website/src directory. The source for man pages is in man/manpages.src.

To generate the acutal website you'll need nodejs and pandoc. Do the following:

$ cd website
$ ./generate.sh

Generated HTML pages are added to the git repository so that they are available even for users without the appropriate toolchain installed.

**Comment by handicraftsman** [comment]
Oh, sorry.
