### ISSUE TITLE
Use c11 threads for libdill ?

### ISSUE THREAD

**Issue by mulle-nat** [sustrik/libdill#174]
I am pondering the use of libdill in my own cross-platform endeavours. I use c11 threads as a default, with pthreads and mintomic as a fallback in [mulle-thread](https://github.com/mulle-c/mulle-thread). 

libdill seems to use just pthreads though. I kinda dislike the chance of having multiple thread libraries in an app. So I could

* fork libdill and use my own library in ctx.c (somewhat of an longtime maintenaince burden though, I have enough on my plate already)
* add c11 code to libdill to be used preferably. Create a pull request. (more work initially and a slight chance of deviation). Then what ?
* ask libdill authors to do the c11 work for me :)

**Comment by sustrik** [comment]
I'd prefer option 2. The amount of required code is probably small enough that it won't be a maintenance burden. Basically, the only thing libdill needs from the threads lib is thread-local storage so that threads don't step on each others state. If the interface for that is not clean enough, we can refactor that.

**Comment by mulle-nat** [comment]
c11 seems to be pretty much based on pthreads, so I wouldn't expect much problems. OK, so I will let you know, if I have something. Thx for responding.

**Comment by mulle-nat** [comment]
I'll close this since I am not going to use libdill.
