### ISSUE TITLE
Stream Channels?

### ISSUE THREAD

**Issue by zbanks** [sustrik/libdill#8]
I wanted to get a feel on what your thoughts were on "streaming" channels (as opposed to message-based).

Let's work with an example: let's say I wanted to handle HTTP responses. 

The natural division would seem to be have two coroutines: one to receive data from a TCP socket and stuff it into a channel (`tcp_handler`), and another to read from the channel and parse the HTTP responses (`http_handler`).
##### Method 1

`tcp_handler` reads packets from TCP, and then writes the whole packet to the channel. (It could write a a pointer, or the whole buffer -- which is more idiomatic here? Currently `chan` doesn't work across `proc()` anyways...). This coroutine is simple.

`http_handler` gets awkward. While parsing the headers, it wants to read line-delimited data. It needs to maintain it's own buffer between channel reads, and then stitch the buffers together. It all works, but it seems like you've reintroduced a state machine and were unable to take advantage of the fact that it's a coroutine.
##### Method 2

`tcp_handler` reads packets from TCP. It then buffers the data and delimits it by newlines. Each newline is written separately into the channel.

`http_handler` now can parse the header very cleanly. However, there's a bug with parsing the response body: it's not required to end with a newline. The parser will for a newline/more data. So this just doesn't work.

Possibly `tcp_handler` could know more about how HTTP works, or `http_handler` could send some type of "mode" information back to `tcp_handler`, but both of these seem too hacky.
##### Method 3

`tcp_handler` reads packets from TCP, and writes the data to a channel which acts as a stream.

`http_handler` can now read with whatever granularity it wants from the channel. 

_Ideally_, it would be great if the API supported peaking into the channel's buffer before removing it -- this would allow `http_handler` to find newlines without having to read 1 byte at a time. (Though, this does make the API more complex)

---

So, thoughts? Does Method 3 have enough merit, or is HTTP just a special-case for being both newline _and_ length delimited? Is there something I'm missing? Otherwise, if it were just newline delimited, I think Method 2 would be best.

**Comment by sustrik** [comment]
You are thinking in the right direction.

Eventually, I would like to have a sane networking library on top of libdill. (See dillsocks for my experiment in the area.)

Sane library means that the protocols are composable:

1. Vertically (e.g. SMTP on top of CRLF-line-protocol on top of TCP on top of IP)
2. Horizontally (e.g. do HTTP header, then switch to HTML)

It is also important (as you correctly point out!) to avoid state machines at all levels of the stack.

My idea so far looks like this:

1. TCP has API to send/recv N bytes. The operation is atomic, you either get N bytes or none. This makes it easy to write binary protocols.
2. CRLF-line-protocol lives on top of TCP (or similar) reads one byte at time and returns full lines to the user.
3. HTTP lives on top of that.
4. After HTTP header is processes, it switches to HTML protocol. As you mention, this is tricky, because the protocol was not designed with layering in mind. (There is similar problem with STARTTLS, for example.) Still, it can be solved dy adding some additional logic to CRLF protocol.

**Comment by zbanks** [comment]
I'm really interested to see how dillsocks comes along. That seems like the ideal use case of libdill. 

I wrote something similar in python - https://github.com/ervanalb/lens . (Fair warning: the code quality is proof-of-concept). There, I handled HTTP exactly as you just described with 4 coroutines. The HTTP layer can signal to the CRLF to turn it on or off for a given connection -- although, this always felt incredibly awkward. This also doesn't work if there's any buffering between the CRLF coroutine & the HTTP one.

----

I also came up with a fourth variation. It seems a bit unidiomatic, but incredibly flexible and would work great for HTTP.

##### Method 4
`tcp_handler` reads data from a TCP stream, and writes it into a (non-channel) buffer it shares with `http_handler`. It then writes a bit to a channel, indicating that there is data.

`http_handler` blocks on receiving channel, and then pulls data out of the (non-channel) buffer. It can freely peek into the buffer without removing data from it. The channel is solely used for scheduling.

----
Maybe this is just a reasonable way of implementing a streaming channel?

**Comment by sustrik** [comment]
Yep. The buffering is the hard part. If the protocol is mis-layered (like HTTP and many other protocols) buffering stops to work.

However, for the philosophical point of view: I'd rather create a clean tool to implement well-designed protocols that messy tool to deal with all the insanity of the existing protocol stack.

That being said, it's often possible to deal with the mislayering using relatively small and benign hacks. E.g. "stop buffering one you see "STARTTLS".

As for method 4, to make it properly one would need infinite look-ahead, otherwise we are back to state machines. That in turn seems to encourage sloppy protocol design.

**Comment by schmurfy** [comment]
For a sane network library you might want to have a look at [mongoose](https://github.com/cesanta/mongoose), while it might not be exactly what you need here it might be a starting point and/or a source of ideas :)
I like the overall design but some points worth mentioning are:
- entirely in C
- easy to embed and easy to work with
- it splits protocol handling from the transport
- it handles many useful protocols (all can be added/removed using defines)
- the library is event based (data available, new connection accepted, connection closed, ...)
- protocol parsing is done by handler functions, the first level is a system handler then a user handler, as an example the http handler will catch read events, read the data then emit a http_request event.

PS: I have no link to them beside being a happy user

**Comment by sustrik** [comment]
The whole reason I've written libdill is to get rid of even-based networking in favour of simple imperative programming. For example: Read N bytes from connection, send M bytes to connection. repeat. And similar.

**Comment by reqshark** [comment]
you mean event-based, like event loop state machine stuff?

**Comment by sustrik** [comment]
I mean event-based as "react to incoming events" -- as opposed to "execute user-specified operations".

**Comment by schmurfy** [comment]
My bad, I missed that xD

**Comment by raedwulf** [comment]
This issue is old.  There is now [dsock](https://github.com/sustrik/dsock).
